name: Credential Security Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [trunk, main, releases/*]
  push:
    branches: [trunk, main, releases/*]  # Optional: scan on direct pushes

env:
  PYTHON_VERSION: '3.11'
  SCAN_DB_PATH: '/tmp/credential-scan/scan.db'

jobs:
  credential-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev sqlite3
        
    - name: Install Credential Digger
      run: |
        pip install --upgrade pip
        pip install credentialdigger

    - name: Get rules from credentialdigger repo
      run : |
        # Download the latest comprehensive rules from Credential Digger's repository
        curl -L -o standard_rules.yml https://github.com/SAP/credential-digger/raw/refs/heads/main/ui/backend/rules.yml
        # add more rules to standard_rules.yml
        cat << EOT >> standard_rules.yml
          - regex: (ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9_]{36}
            category: token
            description: "Github PAT"
        EOT
        echo "✅ Comprehensive rules downloaded"
        
    - name: Setup database and add rules
      run: |
        mkdir -p /tmp/credential-scan
        credentialdigger add_rules --sqlite ${{ env.SCAN_DB_PATH }} standard_rules.yml
        echo "✅ Rules added to database"
        
    - name: Determine scan scope
      id: scope
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          # For PR, scan only changed files
          BASE_SHA=${{ github.event.pull_request.base.sha }}
          HEAD_SHA=${{ github.event.pull_request.head.sha }}
          git diff --name-only $BASE_SHA...$HEAD_SHA | grep -E '\.(py|js|ts|java|go|php|rb|cs|cpp|c|h|yml|yaml|json|xml|env|config|ini|properties|sh|bash)$' > changed_files.txt || true
          echo "scope=pr" >> $GITHUB_OUTPUT
        else
          # For push, scan all files (or recent commits)
          git log --name-only --pretty=format: -n 5 | grep -E '\.(py|js|ts|java|go|php|rb|cs|cpp|c|h|yml|yaml|json|xml|env|config|ini|properties|sh|bash)$' | sort -u > changed_files.txt || true
          echo "scope=push" >> $GITHUB_OUTPUT
        fi
        
        # Filter out binary files and common ignore patterns
        if [[ -f changed_files.txt ]]; then
          grep -v -E '\.(png|jpg|jpeg|gif|ico|svg|pdf|zip|tar|gz|exe|dll|so|dylib)$' changed_files.txt > filtered_files.txt || true
          mv filtered_files.txt changed_files.txt
        fi
        
        echo "Files to scan:"
        if [[ -f changed_files.txt ]]; then
          cat changed_files.txt
          echo "file_count=$(wc -l < changed_files.txt)" >> $GITHUB_OUTPUT
        else
          echo "No files found to scan"
          echo "file_count=0" >> $GITHUB_OUTPUT
        fi
        
    - name: Scan files for credentials
      id: scan
      env:
        # Suppress TensorFlow warnings and CUDA messages
        TF_CPP_MIN_LOG_LEVEL: '3'
        CUDA_VISIBLE_DEVICES: ''
        TF_ENABLE_ONEDNN_OPTS: '0'
      run: |
        if [[ ! -f changed_files.txt ]] || [[ $(wc -l < changed_files.txt) -eq 0 ]]; then
          echo "No files to scan"
          echo "credentials_found=false" >> $GITHUB_OUTPUT
          echo "scan_results=No files found to scan" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Initialize variables
        CREDENTIALS_FOUND=false
        SCAN_RESULTS=""
        DETAILED_RESULTS=""
        TOTAL_FILES=0
        SCANNED_FILES=0
        
        # Create temp directory for scanning
        mkdir -p /tmp/individual-scans
        
        while IFS= read -r file; do
          if [[ -f "$file" ]]; then
            TOTAL_FILES=$((TOTAL_FILES + 1))
            echo "🔍 Scanning: $file"
            
            # Copy file to temp location
            temp_file="/tmp/individual-scans/$(basename "$file")_$$"
            cp "$file" "$temp_file"
            
            # Perform scan with error handling
            SCAN_OUTPUT=""
            SCAN_EXIT_CODE=0
            
            SCAN_OUTPUT=$(credentialdigger scan_path "$temp_file" \
              --sqlite ${{ env.SCAN_DB_PATH }} \
              2>&1) || SCAN_EXIT_CODE=$?

            echo "Scan output for $file:"
            echo "----------------------------------------"
            echo $SCAN_OUTPUT
            echo "----------------------------------------"
            echo "Exit code: $SCAN_EXIT_CODE"
            echo "----------------------------------------"
            
            # Check for credentials
            if [[ $SCAN_EXIT_CODE -ne 0 ]]; then
              SCANNED_FILES=$((SCANNED_FILES + 1))
              CREDENTIALS_FOUND=true
              SCAN_RESULTS="$SCAN_RESULTS❌ **$file**: $SCAN_EXIT_CODE Potential credentials detected\n"
              DETAILED_RESULTS="$DETAILED_RESULTS\n### 🚨 $file\n\`\`\`\n$SCAN_OUTPUT\n\`\`\`\n"
              echo "::error file=$file::Potential credentials detected"
            else
              SCAN_RESULTS="$SCAN_RESULTS✅ **$file**: Clean\n"
            fi
            
            # Cleanup
            rm -f "$temp_file"
          fi
        done < changed_files.txt
        
        # Generate summary
        SUMMARY="📊 **Scan Summary:**\n"
        SUMMARY="${SUMMARY}- Total files: $TOTAL_FILES\n"
        SUMMARY="${SUMMARY}- Successfully scanned: $SCANNED_FILES\n"
        SUMMARY="${SUMMARY}- Status: $([ "$CREDENTIALS_FOUND" = true ] && echo "🚨 CREDENTIALS FOUND" || echo "✅ CLEAN")\n"
        
        # Set outputs
        echo "credentials_found=$CREDENTIALS_FOUND" >> $GITHUB_OUTPUT
        echo "total_files=$TOTAL_FILES" >> $GITHUB_OUTPUT
        echo "scanned_files=$SCANNED_FILES" >> $GITHUB_OUTPUT
        
        # Multi-line outputs
        {
          echo "scan_results<<EOF"
          echo -e "$SCAN_RESULTS"
          echo "EOF"
        } >> $GITHUB_OUTPUT
        
        {
          echo "summary<<EOF"
          echo -e "$SUMMARY"
          echo "EOF"
        } >> $GITHUB_OUTPUT
        
        {
          echo "detailed_results<<EOF"
          echo -e "$DETAILED_RESULTS"
          echo "EOF"
        } >> $GITHUB_OUTPUT
          
    - name: Comment on PR
      if: github.event_name == 'pull_request' && always()
      uses: actions/github-script@v7
      with:
        script: |
          const credentialsFound = '${{ steps.scan.outputs.credentials_found }}' === 'true';
          const totalFiles = '${{ steps.scan.outputs.total_files }}';
          const scannedFiles = '${{ steps.scan.outputs.scanned_files }}';
          
          // Delete previous comments from this action
          const comments = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          
          for (const comment of comments.data) {
            if (comment.user.login === 'github-actions[bot]' && 
                comment.body.includes('Credential Digger Security Scan')) {
              await github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: comment.id,
              });
            }
          }
          
          const statusIcon = credentialsFound ? '🚨' : '✅';
          const statusText = credentialsFound ? 'CREDENTIALS DETECTED' : 'SCAN COMPLETE - NO ISSUES';

          const fixInstructions = `
          1. **Remove Hardcoded Credentials** from your code.
          2. **Use Environment Variables** instead.
          3. **Use Github Secrets** for sensitive data.
          4. **Use files that are not tracked by git**
          5. **Consider using tools to store secrets** like vaults or secret management services.`;
          
          const body = `## ${statusIcon} Credential Digger Security Scan
          
          **Status:** ${statusText}
          
          ${{ steps.scan.outputs.summary }}
          
          ### File Results:
          ${{ steps.scan.outputs.scan_results }}
          
          ${credentialsFound ? 
            '### ⚠️ Action Required\n\nHardcoded credentials were detected in your changes. Please:\n\n1. Remove any hardcoded passwords, API keys, tokens, or secrets\n2. Use environment variables or secure secret management instead\n3. Consider using tools like \`git-secrets\` locally to prevent future issues\n\n**This PR cannot be merged until credentials are removed.**' : 
            '### ✅ All Clear\n\nNo credentials detected in the changed files. Great job maintaining security best practices!'}
          
          'Please check the scan results for details on any detected credentials.'
          
          ---
          <details>
          <summary>🔧 How to fix credential issues</summary>
          
          ${fixInstructions}
            
          </details>
          
          **Scanned ${scannedFiles}/${totalFiles} files in this PR**`;
          
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });
          
    - name: Upload scan database (for debugging)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: credential-scan-db
        path: /tmp/credential-scan/scan.db
        retention-days: 7
        
    - name: Fail build if credentials found
      if: steps.scan.outputs.credentials_found == 'true'
      run: |
        echo "::error title=Security Issue::Hardcoded credentials detected in PR"
        echo ""
        echo "🚨 SECURITY ALERT: Hardcoded credentials were found in your changes!"
        echo ""
        echo "Files with issues:"
        echo "${{ steps.scan.outputs.scan_results }}"
        echo ""
        echo "Please remove all hardcoded credentials before merging this PR."
        echo "Use environment variables, GitHub secrets, or secure config management instead."
        echo ""
        exit 1
        
    - name: Success summary
      if: steps.scan.outputs.credentials_found == 'false'
      run: |
        echo "✅ Security scan completed successfully!"
        echo "📊 Scanned ${{ steps.scan.outputs.scanned_files }} files"
        echo "🔒 No credentials detected - your code is secure!"
